import type { Metadata } from "next";
import "./globals.css";
import { ibmPlexMono, inriaSans, inter } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased text-6xl ${inter.variable} ${ibmPlexMono.variable} ${inriaSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
