import type { Metadata } from "next";
import "./globals.css";
import { ibmPlexMono, inriaSans, inter } from "./fonts/fonts";
import Navbar from "@/components/Navigation/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.variable} ${ibmPlexMono.variable} ${inriaSans.variable} px-[10%] flex flex-col min-h-screen`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
