import type { Metadata } from "next";
import "./globals.css";
import { ibmPlexMono, inriaSans, inter } from "./fonts/fonts";
import Navbar from "@/components/Navigation/NavBar";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/Sessionprovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`antialiased ${inter.variable} ${ibmPlexMono.variable} ${inriaSans.variable}`}
      >
        <SessionProvider>
          <main className="px-[10%] flex flex-col min-h-screen">
            <Navbar />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
